In [1]:
import numpy as np

Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 1 до 20, затем создайте массив состоящий из 10 элементов, начиная с 2. Выведите значения этих массивов, а также их сумму, при помощи функции print()

Создайте массив , состоящий из 7 случайных целых чисел из диапазона от 0 до 9, затем создайте новый массив состоящий из 7 элементов первого массива, увеличенных в 3 раза. Выведите значения этих массивов при помощи функции print()

Создайте массив состоящий из квадратных корней 20 элементов по порядку, начиная с 7. Выведите значение массива при помощи функции print()

In [6]:
array = np.random.randint(1,21,10)
array_2 = np.arange(2,12)
print(array)
print(array_2)
print(array+array_2)

[15 13 18  4 15 17 18 15  1 17]
[ 2  3  4  5  6  7  8  9 10 11]
[17 16 22  9 21 24 26 24 11 28]


In [8]:
array = np.random.randint(0,10,7)
array_2 = array[:]
print(array)
print(array_2*3)


[8 0 6 5 5 6 2]
[24  0 18 15 15 18  6]


In [13]:
array = np.arange(7,27)
print(np.sqrt(array))

[2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152 4.89897949
 5.         5.09901951]
