In [2]:
import numpy as np



Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 1 до 20, затем создайте массив состоящий из 5 элементов, начиная со 2 по порядку. Выведите значения обоих массивов при помощи функции print()

Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 0 до 20, затем создайте массив состоящий из элементов, начиная с третьего по порядку до последнего. Выведите значения обоих массивов при помощи функции print()

Создайте двумерный массив , состоящий из случайных целых чисел из диапазона от 3 до 11, в котором 4 строки и 3 столбца. Затем создайте массив состоящий из элементов , второй и третьей строки и первого и второго столбца по порядку. Выведите значения обоих массивов при помощи функции print()

Создайте двумерный массив , состоящий из случайных целых чисел из диапазона от 0 до 9, в котором 4 строки и 6 столбцов. Затем создайте массив состоящий из элементов , которые больше числа 3. Выведите значения обоих массивов при помощи функции print()

In [29]:
array = np.random.randint(1,21,10)
print(array)
array_2 = array[2:7]
print(array_2)

[20 16  5 20 10 18  6 20  7 15]
[ 5 20 10 18  6]


In [30]:
array = np.random.randint(0,20,10)
array_2 = array[3:]
print(array)
print(array_2)

[ 0  8  8  0  4 10 19  4 12 12]
[ 0  4 10 19  4 12 12]


In [3]:
array = np.random.randint(3,12, 12).reshape(4,3)
print(array)
print()
print(array[1:3][0:2])

[[ 9  3  5]
 [10  6  9]
 [ 4  9 11]
 [11  6  9]]

[[10  6  9]
 [ 4  9 11]]


In [36]:
array = np.random.randint(0,9, 24).reshape(4,6)
print(array)
print(array[array>3])


[[4 6 7 8 2 2]
 [3 4 6 6 0 3]
 [1 6 2 8 5 6]
 [4 3 2 4 0 4]]
[4 6 7 8 4 6 6 6 8 5 6 4 4 4]
