In [6]:
import numpy as np

Создайте массив из списка, , состоящего из чисел от 0 до 9, при помощи функции array() из модуля numpy

Создайте массив , состоящий из нечётных чисел от 1 до 19, при помощи функции arange() из модуля numpy

Создайте массив , состоящий из двадцати нулей

Создайте двумерный массив , состоящий из двадцати единиц, в котором 5 строк и 4 столбца

Создайте массив , состоящий из пяти равномерно распределённых чисел от 3 до 7

Создайте двумерный массив , состоящий из 9 равномерно распределённых чисел от 3 до 7

Создайте массив , состоящий из 10 случайных целых чисел из диапазона от 1 до 100, присвойте его максимальное значение переменной max_number и выведите значение этой переменной при помощи функции print()

In [5]:
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [10]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [11]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
array_1 = np.random.randint(3,8,5)
print(array_1)

[6 5 4 3 5]


In [28]:
np.array(np.random.randint(3,8,9)).reshape(3,3)

array([[7, 3, 6],
       [7, 5, 3],
       [3, 3, 7]])

In [32]:
max_number = np.random.randint(1,100,10).max()
print(max_number)

96
